# Generated by Django 4.1.1 on 2022-09-22 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('nopagado', 'No Pagado'), ('pagado', 'Pagado')], default='nopagado', max_length=10)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_orden_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
