# Generated by Django 4.1.1 on 2022-09-30 01:43

from django.db import migrations, models
import inventario.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_ordenproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'permissions': [('reporte_cantidad', 'Visualizar el reporte de cantidad'), ('reporte_detalle', 'Reporte detallado de cantidades')]},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[inventario.validators.validar_nombre_categoria]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[inventario.validators.validar_par]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidades',
            field=models.CharField(choices=[('u', 'Unidades'), ('kg', 'Kilogramos')], default='u', max_length=2),
        ),
    ]
